version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    image: climate-data-db
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PGUSER:-admin}
      - POSTGRES_PASSWORD=${PGPASSWORD:-admin}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: climate-data-backend
    container_name: climate-data-backend
    ports:
      - '8000:80'
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGUSER=${PGUSER:-admin}
      - PGPASSWORD=${PGPASSWORD:-admin}
      - PGHOST=${PGHOST:-postgres}
      - PGDATABASE=${PGDATABASE:-postgres}

  import:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: climate-data-import
    container_name: climate-data-import
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGUSER=${PGUSER:-admin}
      - PGPASSWORD=${PGPASSWORD:-admin}
      - PGHOST=${PGHOST:-postgres}
      - PGDATABASE=${PGDATABASE:-postgres}
    volumes:
      - ./data:/app/data
    entrypoint:
      - python
      - /app/scripts/import.py

volumes:
  data: